import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";

const LibreCaslonDisplay = localFont({
  src: "./fonts/LibreCaslonDisplay-Regular.ttf",
  variable: "--font-libre-caslon-display",
  weight: "100 900",
});
const Poppins = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LibreCaslonDisplay.variable} ${Poppins.variable} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
